# Generated by Django 4.0.3 on 2022-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P4214', '0004_clothes_cid_alter_clothes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='cid',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
